name: DesignHamptons
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: 'Design Hamptons - Fashion, Beauty & Design'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.260853
  lightness: 0.5859331
  saturation: 0.3071721
  rhythmicContrast: 0.1473709
purpose: []
